# Generated by Django 4.0.6 on 2022-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0003_tguser_remove_trigger_tg_user_id_trigger_tg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='theater_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
