# Generated by Django 4.0.6 on 2022-07-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0002_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TktnewData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
