# Generated by Django 4.0.6 on 2022-07-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0002_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='tg_user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
