# Generated by Django 4.0.6 on 2022-07-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0002_rename_film_trigger_movie_trigger_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGuser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='tg_user_id',
        ),
        migrations.AddField(
            model_name='trigger',
            name='tg_user',
            field=models.ForeignKey(default='unavailable', on_delete=django.db.models.deletion.CASCADE, related_name='tg_user_id', to='ticketsense.tguser'),
            preserve_default=False,
        ),
    ]
