# Generated by Django 4.0.6 on 2022-07-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0003_trigger_tg_user_id_alter_trigger_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
