# Generated by Django 4.0.6 on 2022-07-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='film',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='trigger',
            name='poster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='release_year',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='theater',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
